FROM golang:1.10-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /go-caelum
RUN cd /go-caelum && make bootnode

RUN chmod +x /go-caelum/build/bin/bootnode

FROM alpine:latest

LABEL maintainer="etienne@go-caelum.com"

WORKDIR /go-caelum

COPY --from=builder /go-caelum/build/bin/bootnode /usr/local/bin/bootnode

COPY docker/bootnode ./

EXPOSE 30301

ENTRYPOINT ["./entrypoint.sh"]

CMD ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
